#!/bin/bash
here=`dirname "$0"`
export ZEPHYR_SDK_INSTALL_DIR=/opt

if [ -d $ZEPHYR_SDK_INSTALL_DIR/zephyr-sdk-hosttools ]; then
    . $ZEPHYR_SDK_INSTALL_DIR/zephyr-sdk-hosttools/environment-setup-*
fi

for dir in "$ZEPHYR_SDK_INSTALL_DIR"/* "$ZEPHYR_SDK_INSTALL_DIR"/qemu*; do
    if [ -d "$dir" -a -d "$dir"/bin ]; then
	PATH="$dir"/bin:$PATH
    fi
done

# Override the default qemu-system-mips
# https://github.com/zephyrproject-rtos/sdk-ng/issues/849
bindir="$here/.local/bin"
mkdir -p "$bindir"
ln -sf /usr/bin/qemu-system-mips "$bindir/qemu-system-mips"
ln -sf /usr/bin/qemu-system-mipsel "$bindir/qemu-system-mipsel"
PATH="$bindir":$PATH

exec "$@"
